### ISSUE TITLE
"IndexError: tuple index out of range" on Cloze cards. 

### ISSUE THREAD

**Issue by AlexanderHanson** [glutanimate/sequence-inserter#1]
I was having trouble getting it to insert list items into the Cloze template, specifically ||pick::Style::{{Computer Language}}||. But it was just showing up as text with: ||pick::Style::2||. 

When I tried to get anything to show up, with ||set::int::2|| it threw this error.

Traceback (most recent call last):
  File "aqt\clayout.py", line 224, in saveCard
  File "aqt\clayout.py", line 234, in renderPreview
  File "anki\cards.py", line 120, in q
  File "anki\cards.py", line 137, in _getQA
  File "C:\Users\Alexander\Documents\Anki\addons\sequence_inserter\main.py", line 90, in _renderQA
    html = formatTagString(format_str, replacements)
  File "C:\Users\Alexander\Documents\Anki\addons\sequence_inserter\main.py", line 113, in formatTagString
    formatted = format_str.format(*replacements)
IndexError: tuple index out of range

**Comment by glutanimate** [comment]
Thanks for the report.

What does your `Style` collection look like? There might be some special characters causing issues.

**Comment by AlexanderHanson** [comment]
```
Style = ["background-color: #b3b300;", # C++, value for the field should be 1.
"background: #003300; color: lightgrey; text-shadow: 1px 1px grey; letter-spacing: 1px;", # HTML / CSS, value for the fields should be 2.
"background-color: Bisque;"
]
```
```
collections = {
	"Style": Style,
	"ColorNames": ColorNames,
	"LangName": LangName
}

```
Just to clarify, this is how I am using it on a Basic card template and it works fine.
```
<div style="||pick::Style::{{Computer Language}}||">

{{Front}}

</div>
```
In the Cloze cards, it was just displaying the tag ||pick::Style::2||.
The error occurs sporadically when using ||set::int::1||. 

I have also learned that both tags work correctly if they are placed on the back template like this:

```
{{cloze:Text}}<br>
{{Extra}}||pick::Style::{{Code Language}}||
```

Looking over the code I think there is some odd interaction with how the Cloze template is processed in Anki, and how you are replacing braces in the formatTagString() function on line 114 of main.py. I wish I could help more, but I do not know Python.

**Comment by glutanimate** [comment]
Ah, I remember your YouTube comment now! That's quite an interesting use case and something I hadn't considered.

I think you're right. This must have something to do with how Cloze templates are processed. I do know that the templating engine treats clozes in a special way, so there might be some weird interaction going on there.

I'll try to investigate this when I have some more time on my hands, but it might be a while until then.
