### ISSUE TITLE
Wrap selected text in sequence tags

### ISSUE THREAD

**Issue by lucasndv** [glutanimate/sequence-inserter#2]
Hi
Awesome project.
Do you know how can i put the code in a hotkey or a button?
ex:

The **law,order** need the **citzen,government** to end war.
pressing Ctrl+Shift+1 or etc

||rpick::1|law,order||
||rpick::2|citzen,government||

**Comment by glutanimate** [comment]
Hi Lucas,

the latest release of the add-on comes with customizable buttons/hotkeys. It's not available on AnkiWeb, yet, but you can grab it [here](https://github.com/glutanimate/sequence-inserter/releases). As with all other config options the buttons can be set up by modifying your local copy of the cols.py file.

**Comment by lucasndv** [comment]
Hi!

Ocurred an error

Traceback (most recent call last):
  File "aqt\webview.py", line 152, in _linkHandler
  File "aqt\toolbar.py", line 74, in _linkHandler
  File "aqt\toolbar.py", line 88, in _addLinkHandler
  File "aqt\main.py", line 706, in onAddCard
  File "aqt\__init__.py", line 61, in open
    
  File "aqt\addcards.py", line 26, in __init__
  File "aqt\addcards.py", line 40, in setupEditor
  File "aqt\editor.py", line 279, in __init__
  File "anki\hooks.py", line 55, in repl
  File "anki\hooks.py", line 55, in repl
  File "anki\hooks.py", line 56, in repl
  File "\Documents\Anki\addons\power_format_pack\extra_buttons.py", line 72, in setup_buttons
    check=False)
  File "Documents\Anki\addons\sequence_inserter\main.py", line 196, in create_button
    self.seq_btnbox.addWidget(button)
AttributeError: 'Editor' object has no attribute 'seq_btnbox'

**Comment by glutanimate** [comment]
Might be an incompatibility with the Power Format Pack. Does the error message disappear if you remove that add-on?

**Comment by lucasndv** [comment]
Yes, i removed and its working now!

But theres a way to do what i described?

Because i have a lot of text...and in the exams they change pieces of the text.
I'd like to "select part of text" press the button/hokey 
Example:
Text... SpecifWord,WrongWord1,WrongWord2 ...text
(I'll Press the button/hotkley on the words and will generate ||rpick::**1**|SpecifWord,WrongWord1,WrongWord2||

**Comment by glutanimate** [comment]
Ok, glad to hear that!

Ah, I see what you mean now. That would be useful, indeed. Unfortunately I can't work on any additional features right now as I'm very short on time, but I will definitely keep this in mind for when I find some free development time.  I will also see if there's any easy way to resolve that compatibility issue with the PFP.

Thanks again for the suggestion!
